import type { Metadata } from "next";
import { StackProvider, StackTheme, useUser } from "@stackframe/stack";
import { stackClientApp } from "../stack/client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const theme = {
  light: {
    primary: '#52796F',
    input: '#84A98C'
  },
  dark: {
    primary: '#52796F',
  },
  radius: '8px',
 
}
// ...

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-cambridge-blue-0`}
      ><StackProvider app={stackClientApp}><StackTheme theme={theme}>
        {children}
      </StackTheme></StackProvider></body>
    </html>
  );
}
